# Generated by Django 5.2.8 on 2025-12-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_options_alter_chapter_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='enrolled_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
