# Generated by Django 5.2.8 on 2025-12-04 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_chapter_title_alter_enrollment_enrolled_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InstructorProfiles',
            new_name='InstructorProfile',
        ),
    ]
