# Generated by Django 5.2.8 on 2025-12-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_chapter_course_alter_lesson_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Nam'), ('female', 'Nữ')], max_length=10, null=True),
        ),
    ]
