# Generated by Django 5.2.8 on 2025-12-31 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_user_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='duration_minutes',
        ),
    ]
